DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 500
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "adam"
  LR: 0.002
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 5

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  COOP:
    N_CTX: 4
    CSC: False
    CTX_INIT: False
    PREC: "fp16"
    CLASS_TOKEN_POSITION: "end"
    W: 8.0
  COCOOP:
    PREC: "fp16"
  TCP_MOD_MMA:
    # Enable adapters (set to false to use original TCP_MOD behavior)
    USE_ADAPTERS: true
    
    # Adapter settings (applies to both text and visual encoders)
    ADAPTER_START: 6         # Start applying adapters from layer 6
    ADAPTER_END: 11          # End applying adapters at layer 11 (ViT-B/16 has 12 layers, 0-11)
    
    # Adapter architecture settings
    ADAPTER_DIM: 64          # Adapter bottleneck dimension
    ADAPTER_SCALE: 0.5       # Adapter scaling factor
    
    # Text context initialization for adapters
    TEXT_CTX_INIT: "a photo of a"
    
    # Precision settings
    PREC: "fp16"
